=== flowcentraltechnologies/flowcentral/flowcentral-configuration/src/main/resources/xsd/flowcentral-module-4.0.0.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
   	targetNamespace="http://flowcentraltech.com/schema-common"
   	xmlns="http://flowcentraltech.com/schema-common"
	attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:include schemaLocation="flowcentral-types.xsd"/>
  <!-- Module -->
  <xs:element name="module">
    <xs:complexType>
      <xs:all>
        <xs:element name="applications" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="application" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute type="xs:string" name="name" use="required"/>
                  <xs:attribute type="xs:string" name="shortDescription" use="required"/>
                  <xs:attribute type="xs:string" name="longDescription" use="required"/>
                  <xs:attribute type="xs:boolean" name="autoInstall" use="optional"/>
                  <xs:attribute type="xs:string" name="configFile" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="sysParameters" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="sysParameter" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:attribute name="type" use="optional">
			        <xs:simpleType>
			          <xs:restriction base="xs:string">
			            <xs:enumeration value="BOOLEAN"/>
			            <xs:enumeration value="NUMBER"/>
			            <xs:enumeration value="STRING"/>
			            <xs:enumeration value="NAME"/>
			            <xs:enumeration value="CONTACT"/>
			          </xs:restriction>
			        </xs:simpleType>
			      </xs:attribute>
                  <xs:attribute type="xs:string" name="code" use="required"/>
                  <xs:attribute type="xs:string" name="description" use="required"/>
                  <xs:attribute type="xs:string" name="editor" use="required"/>
                  <xs:attribute type="xs:string" name="defaultVal" use="optional"/>
                  <xs:attribute type="xs:string" name="filter" use="optional"/>
                  <xs:attribute type="xs:boolean" name="control" use="optional"/>
                  <xs:attribute type="xs:boolean" name="editable" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
      <xs:attribute type="xs:string" name="name" use="required"/>
      <xs:attribute type="xs:string" name="description" use="required"/>
      <xs:attribute type="xs:string" name="shortCode" use="required"/>
      <xs:attribute type="xs:string" name="label" use="required"/>
      <xs:attribute type="xs:boolean" name="principal" use="optional"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== flowcentraltechnologies/flowcentral/flowcentral-report/src/main/resources/config/report-module.xml
<?xml version="1.0"?>
<!-- Master report module configuration -->
<module
	xmlns="http://flowcentraltech.com/schema-common"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://flowcentraltech.com/schema-common file:///C:/data/flowcentral-module-4.0.0.xsd"
	name="report" description="$m{report.module}" shortCode="RPT"
	label="$m{report.label}">
	<!-- Applications -->
	<applications>
		<application name="report"
			shortDescription="$m{report.short.description}"
			longDescription="$m{report.long.description}" autoInstall="true"
			configFile="apps/report-application.xml" />
	</applications>
	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="RPT-0001" defaultVal="web/report/templates/"
			description="$m{report.sysparam.reporttemplatepath}" editor="!ui-text size:40"
			type="STRING" editable="true"/>
		<sysParameter code="RPT-0002" defaultVal="web/images/applicationloginbanner.png"
			description="$m{report.sysparam.reportclientlogo}" editor="!ui-text size:40"
			type="STRING" editable="true"/>
		<sysParameter code="RPT-0003" defaultVal="dynamicreportportrait.jrxml"
			description="$m{report.sysparam.dynamicreportportraittemplate}"
			editor="!ui-text size:40" type="STRING" editable="true"/>
		<sysParameter code="RPT-0004" defaultVal="dynamicreportlandscape.jrxml"
			description="$m{report.sysparam.dynamicreportlandscapetemplate}"
			editor="!ui-text size:40" type="STRING" editable="true"/>
		<sysParameter code="RPT-0005" defaultVal="2"
			description="$m{report.sysparam.reportlistingcolumns}"
			editor="!ui-select list:onetotenlist" type="NUMBER" editable="true"/>
	</sysParameters>
</module>

=== flowcentraltechnologies/flowcentral/flowcentral-workflow/src/main/resources/config/workflow-module.xml
<?xml version="1.0"?>
<!-- Workflow module configuration -->
<module
	xmlns="http://flowcentraltech.com/schema-common"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://flowcentraltech.com/schema-common file:///C:/data/flowcentral-module-4.0.0.xsd"
	name="workflow" description="$m{workflow.module}" shortCode="WRK"
	label="$m{workflow.label}">
	<!-- Applications -->
	<applications>
		<application name="workflow"
			shortDescription="$m{workflow.short.description}"
			longDescription="$m{workflow.long.description}" autoInstall="true"
			configFile="apps/workflow-application.xml" />
		<application name="workflowDraft"
			shortDescription="$m{workflow.draft.short.description}"
			longDescription="$m{workflow.draft.long.description}" autoInstall="true"
			configFile="apps/workflow-draft-application.xml" />
	</applications>

	<!-- System Parameters -->
	<sysParameters>
		<sysParameter code="WF-0001" defaultVal="64"
			description="$m{workflow.sysparam.processingbatchsize}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="WF-0002" defaultVal="64"
			description="$m{workflow.sysparam.autoloadingbatchsize}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="WF-0003" defaultVal="true"
			description="$m{workflow.sysparam.enableupdateonreview}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="WF-0004" defaultVal="true"
			description="$m{workflow.sysparam.enableautoloading}"
			editor="!ui-select list:booleanlist" type="BOOLEAN" editable="true" />
		<sysParameter code="WF-0005" defaultVal="64"
			description="$m{workflow.sysparam.itemalertbatchsize}"
			editor="!ui-integer precision:2" type="NUMBER" editable="true" />
		<sysParameter code="WF-0006" defaultVal="196"
			description="$m{workflow.sysparam.itemejectionbatchsize}"
			editor="!ui-integer precision:4" type="NUMBER" editable="true" />
	</sysParameters>
</module>
